apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  targetNamespaces:
    - "{{ .Values.namespace }}"