## CURRENTLY NOT AVAILABLE BUT IS IN OPEN PR
## HOPING FOR IMPLEMENTATION SOON
## UNTIL THEN KYVERNO OR ANSIBLE MAY DO THIS

## LEAVING TO REMIND ME TO CHECK - https://github.com/external-secrets/external-secrets/pull/3449

# apiVersion: external-secrets.io/v1alpha1
# kind: ExternalSecret
# metadata:
#   name: patch-gitlab-ca
#   namespace: openshift-gitops
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: eso-admin-secret-store
#     kind: ClusterSecretStore
#   target:
#     name: argocd-tls-certs-cm
#     creationPolicy: Merge
#     template:
#       data:
#         "gitlab.{{ .Values.domain }}": |
#           {{ `{{ .CFSSL_CA }}` }}
#   data:
#     - secretKey: "CFSSL_CA"
#       remoteRef:
#         key: "gitlab"
#         property: "cfssl_ca"