apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: trustification-monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: trustification
  name: trustification-monitoring
spec:
  ports:
  - name: metrics
    port: 9010
    protocol: TCP
    targetPort: 9010
  selector:
    app.kubernetes.io/part-of: trustification
    metrics: "true"
  type: ClusterIP
