apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: amq-streams-2.9.x
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v2.9.2-1
  config:
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: 200m
        memory: 386Mi

