{{- if .Values.deployMinio }}
---
kind: Secret
apiVersion: v1
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: trustification
    app.kubernetes.io/part-of: trustification
data:
  username: {{ "admin" | b64enc }}
  password: {{ "password" | b64enc }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.bombastic.credentials }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: trustification
    app.kubernetes.io/part-of: trustification
data:
  aws_access_key_id: {{ "admin" | b64enc }}
  aws_secret_access_key: {{ "password" | b64enc }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.v11y.credentials }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: trustification
    app.kubernetes.io/part-of: trustification
data:
  aws_access_key_id: {{ "admin" | b64enc }}
  aws_secret_access_key: {{ "password" | b64enc }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.vexination.credentials }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: trustification
    app.kubernetes.io/part-of: trustification
data:
  aws_access_key_id: {{ "admin" | b64enc }}
  aws_secret_access_key: {{ "password" | b64enc }}
{{ end }}