{{ if .Values.deployMinio }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: trustification
  name: minio
spec:
  ports:
  - name: endpoint
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: trustification
  type: ClusterIP
{{ end }}
