{{- if .Values.deployMinio }}
kind: Job
apiVersion: batch/v1
metadata:
  name: post-install-minio
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
    helm.sh/hook-weight: "4"
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/name: post-install-minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: trustification

spec:
  backoffLimit: 1000
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:

      restartPolicy: OnFailure

      containers:
        - name: post-install
          image: {{ .Values.minio.cliImage }}
          imagePullPolicy: IfNotPresent

          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: minio
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: minio

          command:
            - bash
            - -exc
            - |
                /usr/bin/mc config host add myminio http://minio.{{ .Release.Namespace}}.svc.cluster.local:9000 "${USER}" "${PASSWORD}";
                /usr/bin/mc mb myminio/bombastic --ignore-existing;
                /usr/bin/mc policy download myminio/bombastic;
                /usr/bin/mc event add myminio/bombastic arn:minio:sqs::BOMBASTIC:kafka --event "put,delete" --ignore-existing;

                /usr/bin/mc mb myminio/vexination --ignore-existing;
                /usr/bin/mc policy download myminio/vexination;
                /usr/bin/mc event add myminio/vexination arn:minio:sqs::VEXINATION:kafka --event put --ignore-existing;

                /usr/bin/mc mb myminio/v11y --ignore-existing;
                /usr/bin/mc policy download myminio/v11y;
                /usr/bin/mc event add myminio/v11y arn:minio:sqs::V11Y:kafka --event put --ignore-existing;

                /usr/bin/mc admin service restart myminio;
          volumeMounts:
            - mountPath: /.mc
              name: settings
      volumes:
        - name: settings
          emptyDir: {}
{{ end }}

