{{ if .Values.chains.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: signing-secret
  namespace: openshift-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: signing-secrets
    template:
      metadata:
        labels:
          rhtas.redhat.com/signing-secret: 'true'
      type: generic
  data:
    - secretKey: "cosign.pub"
      remoteRef:
        key: signing
        property: "cosign.pub"
    - secretKey: "cosign.key"
      remoteRef:
        key: signing
        property: "cosign.key"
    - secretKey: "cosign.password"
      remoteRef:
        key: signing
        property: "cosign.password"
{{ end }}