{{- if .Values.deployPostgres }}
kind: Secret
apiVersion: v1
metadata:
  name: guac-admin-db
  labels:
    app.kubernetes.io/name: guac-admin-db
    app.kubernetes.io/component: guac
    app.kubernetes.io/part-of: guac
data:
  db.host: {{ .Values.postgres.host | default "postgres" | b64enc }}
  db.port: {{ .Values.postgres.port | default "5432" |  b64enc }}
  db.name: {{ .Values.postgres.name | default "guac" | b64enc }}
  db.user: {{ .Values.postgres.user | default "postgres" | b64enc }}
  db.password: {{ .Values.postgres.password | default "guac1234" | b64enc }}
  db.options: {{ .Values.postgres.options | default "?sslmode=disable" | b64enc }}
---
kind: Secret
apiVersion: v1
metadata:
  name: guac-user-db
  labels:
    app.kubernetes.io/name: guac-user-db
    app.kubernetes.io/component: guac
    app.kubernetes.io/part-of: guac
data:
  db.host: {{ .Values.postgres.host | default "postgres" | b64enc }}
  db.port: {{ .Values.postgres.port | default "5432" |  b64enc }}
  db.name: {{ .Values.postgres.name | default "guac" | b64enc }}
  db.user: {{ .Values.postgres.user | default "postgres" | b64enc }}
  db.password: {{ .Values.postgres.password | default "guac1234" | b64enc }}
  db.options: {{ .Values.postgres.options | default "?sslmode=disable" | b64enc }}
{{ end }}
