{{- if .Values.deployPostgres }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    app.kubernetes.io/name: postgres-pvc
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: guac
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize | default "10Gi" | quote }}
  {{- with .Values.postgres.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{ end }}
