{{ if .Values.guac.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: guac-collectsub
    app.kubernetes.io/component: collectsub
    app.kubernetes.io/part-of: trustification
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: guac-collectsub-tls
  name: guac-collectsub
spec:
  ports:
  - name: endpoint
    port: 2782
    protocol: TCP
    targetPort: 2782
  selector:
    app.kubernetes.io/name: guac-collectsub
    app.kubernetes.io/component: collectsub
    app.kubernetes.io/part-of: trustification
  type: ClusterIP
{{ end }}
