{{ if .Values.collectorist.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: collectorist-storage
  labels:
    app.kubernetes.io/name: collectorist-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: trustification
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ end }}
