{{ if .Values.collectorist.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: collectorist-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: trustification
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: collectorist-api-tls
  name: collectorist-api
spec:
  ports:
  - name: endpoint
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: collectorist-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: trustification
  type: ClusterIP
{{ end }}
