apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ansible-runner-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
- kind: ServiceAccount
  name: ansible-runner
  namespace: managed-machine-sets
roleRef:
  kind: ClusterRole
  name: ansible-runner-role
  apiGroup: rbac.authorization.k8s.io
