{{- if eq .Values.machineset.enabled true }}
{{ range .Values.machinesets }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}-create-machineset
spec:
  template:
    spec:
      serviceAccountName: ansible-runner
      containers:
      - name: {{ .name }}-ansible-config
        image: registry.access.redhat.com/ubi9/python-311:latest
        command: ["/bin/bash", "-c"]
        env:
          - name: MANAGED_MACHINE_TYPE
            value: "{{ .machine_type }}"
        args:
          - |
            pip install ansible;
            pip install openshift;
            ansible-galaxy collection install community.kubernetes;
            ansible-playbook /etc/ansible/playbook.yaml;
        volumeMounts:
        - name: playbook-volume
          mountPath: /etc/ansible
      volumes:
      - name: playbook-volume
        configMap:
          name: ansible-playbook
      restartPolicy: Never
{{end}}
{{- end }}