{{ if .Values.csafSnapshot }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csaf-snapshot
  labels:
    app.kubernetes.io/name: csaf-data
    app.kubernetes.io/component: csaf
    app.kubernetes.io/part-of: csaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: csaf-data
      app.kubernetes.io/component: csaf
      app.kubernetes.io/part-of: csaf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csaf-data
        app.kubernetes.io/component: csaf
        app.kubernetes.io/part-of: csaf
    spec:
      volumes:
        - name: run
          emptyDir: {}
      containers:
        - image: ghcr.io/trustification/csaf-snapshot:20230605-2
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          volumeMounts:
            - name: run
              mountPath: /run
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
{{ end }}
