apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "rosa-token"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "kubernetes-secrets-store"
    kind: ClusterSecretStore
  target:
    name: "rosa-token"
    template:
      type: generic
      data:
        ROSA_TOKEN: "{{`{{ .ROSA_TOKEN }}`}}"
        AWS_ACCESS_KEY_ID: "{{`{{ .AWS_ACCESS_KEY_ID }}`}}"
        AWS_SECRET_ACCESS_KEY: "{{`{{ .AWS_SECRET_ACCESS_KEY }}`}}"
  data:
    - secretKey: "ROSA_TOKEN"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "rosa-token"
        property: token
    - secretKey: "AWS_ACCESS_KEY_ID"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "aws-credentials"
        property: AWS_ACCESS_KEY_ID
    - secretKey: "AWS_SECRET_ACCESS_KEY"
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "aws-credentials"
        property: AWS_SECRET_ACCESS_KEY
