apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "push-secret-openshift-client"
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: eso-admin-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: keycloak-client-secret-openshift
  data:
    - match:
        secretKey: "CLIENT_SECRET"
        remoteRef:
          remoteKey: keycloak-client-secret-openshift
          property: "CLIENT_SECRET"
    - match:
        secretKey: "CLIENT_ID"
        remoteRef:
          remoteKey: keycloak-client-secret-openshift
          property: "CLIENT_ID"