apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "push-secret-credential-keycloak"
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: eso-admin-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: credential-keycloak
  data:
    - match:
        secretKey: "ADMIN_PASSWORD"
        remoteRef:
          remoteKey: credential-keycloak
          property: "ADMIN_PASSWORD"
    - match:
        secretKey: "ADMIN_USERNAME"
        remoteRef:
          remoteKey: credential-keycloak
          property: "ADMIN_USERNAME"