apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: openshift
  labels:
    realm: openshift
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: Openshift Authentication Realm
    enabled: true
    id: openshift
    realm: openshift
