{{- if .Values.deployKafka }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: trustification
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/component: storage
      app.kubernetes.io/part-of: trustification
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
        app.kubernetes.io/component: storage
        app.kubernetes.io/part-of: trustification
    spec:

      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          imagePullPolicy: IfNotPresent

          env:
            - name: BITNAMI_DEBUG
              value: "yes"
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-controller:9093"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9094,CONTROLLER://:9093,EXTERNAL://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9094,EXTERNAL://localhost:9092"
            - name: KAFKA_HEAP_OPTS
              value: "-verbose:gc" # Let Java figure it out
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "3nA2qspzReOmcxqlkmITAA"

          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            exec:
              command:
                - kafka-topics.sh
                - --bootstrap-server
                - localhost:9094
                - --list

          ports:
            - containerPort: 9093
              name: controller
              protocol: TCP
            - containerPort: 9094
              name: endpoint
              protocol: TCP

          resources:
            {{- with .Values.kafka.resources }}
            {{ . | toYaml | nindent 12 }}
            {{- else }}
            limits:
              memory: 512Mi
            {{- end }}

          volumeMounts:
            - mountPath: /bitnami/kafka
              name: storage

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: kafka-pvc

{{ end }}

