{{ if .Values.deployKafka }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: trustification
  name: kafka
spec:
  ports:
  - name: endpoint
    port: 9094
    protocol: TCP
    targetPort: 9094
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: trustification
  type: ClusterIP
{{ end }}
