{{ if .Values.deployKafka }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kafka-controller
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: trustification
  name: kafka-controller
spec:
  ports:
  - name: controller
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: trustification
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
{{ end }}
