{{ if and .Values.enableDocs .Values.createRoutes }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: trust-docs
    app.kubernetes.io/component: documentation
    app.kubernetes.io/part-of: trustification
  name: trust-docs
spec:
  host: "docs.{{ .Values.domain }}"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: endpoint
  to:
    kind: Service
    name: trust-docs
    weight: 100
  wildcardPolicy: None
{{ end }}
