{{ if .Values.bombastic.walker.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bombastic-walker
  labels:
    app.kubernetes.io/name: bombastic-walker
    app.kubernetes.io/component: walker
    app.kubernetes.io/part-of: trustification
spec:
  schedule: {{ .Values.bombastic.walker.schedule | default "0 1 * * *" }}
  suspend: {{ .Values.bombastic.walker.suspend | default false }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: bombastic-walker
            app.kubernetes.io/component: walker
            app.kubernetes.io/part-of: trustification
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: walker-state
              persistentVolumeClaim:
                claimName: bombastic-walker-state
          containers:
            - image: {{ .Values.trustImage }}:{{ .Values.release }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              name: walker
              command: ["/trust"]
              args:
                - "bombastic"
                - "walker"
                - "--sink"
                - "https://sbom.{{ .Values.domain }}"
                - "--source"
                - "{{ .Values.bombastic.walker.source }}"
                - "-3"
                - "--signing-key"
                - "{{ .Values.bombastic.walker.signingKey }}"
                - "--fix-licenses"
                - "true"
                - "--since-file"
                - "/walker-state/since"
              env:
                - name: RUST_LOG
                  value: {{ default "info" .Values.bombastic.walker.logLevel }}
                - name: INFRASTRUCTURE_ENABLED
                  value: "true"
                - name: INFRASTRUCTURE_BIND
                  value: "[::]:9010"
                {{ include "trustification.authentication-client" ( dict "root" . "clientId" "walker" ) | nindent 16 }}
              ports:
                - containerPort: 9010
                  protocol: TCP
                  name: infra
              volumeMounts:
                - mountPath: /walker-state
                  name: walker-state
              resources:
                {{- toYaml .Values.bombastic.walker.resources | nindent 16 }}
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: 9010
                initialDelaySeconds: 2
              readinessProbe:
                httpGet:
                  path: /health/ready
                  port: 9010
                initialDelaySeconds: 2
              startupProbe:
                httpGet:
                  path: /health/startup
                  port: 9010
{{ end }}
