{{ if .Values.collector.snyk.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-snyk
  labels:
    app.kubernetes.io/name: collector-snyk
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: trustification
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: collector-snyk
      app.kubernetes.io/component: collector
      app.kubernetes.io/part-of: trustification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: collector-snyk
        app.kubernetes.io/component: collector
        app.kubernetes.io/part-of: trustification
        metrics: "true"
      annotations:
        config/checksum: {{ include (print $.Template.BasePath "/config/020-ConfigMap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ .Values.config.name }}
        {{ include "trustification.http-server-volumes" (dict "root" . "appName" "collector-snyk") | nindent 8 }}
      containers:
        - image: {{ .Values.trustImage }}:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          command: ["/trust"]
          args:
            - "collector"
            - "snyk"
            - "-p"
            - "8080"
            - "--auth-configuration"
            - "/etc/config/auth.yaml"
            - "--v11y-url"
            - "https://v11y-api.$(NAMESPACE).svc"
            - "--guac-url"
            - "http://guac-graphql.$(NAMESPACE).svc:8080/query"
          env:
            - name: RUST_LOG
              value: {{ default "info" .Values.collector.snyk.logLevel }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SNYK_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.collector.snyk.credentials }}"
                  key: snyk_org_id
            - name: SNYK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.collector.snyk.credentials }}"
                  key: snyk_token
            {{ include "trustification.http-server" . | nindent 12 }}
            - name: INFRASTRUCTURE_ENABLED
              value: "true"
            - name: INFRASTRUCTURE_BIND
              value: "[::]:9010"
            - name: SWAGGER_UI_OIDC_ISSUER_URL
              {{ include "trustification.authentication-frontend-issuer-url" . | nindent 14 }}
            {{ include "trustification.authentication-client" ( dict "root" . "clientId" "walker" ) | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - mountPath: /etc/config
              name: config
            {{ include "trustification.http-server-volume-mounts" . | nindent 12 }}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9010
              protocol: TCP
              name: infra
          resources:
            {{- toYaml .Values.collector.snyk.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9010
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9010
            initialDelaySeconds: 2
          startupProbe:
            httpGet:
              path: /health/startup
              port: 9010
{{ end }}
