apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: local-cluster
  labels:
    name: local-cluster
    cluster.open-cluster-management.io/clusterset: local-cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hubAcceptsClient: true
