---
# Filebeat is an Elastic Beat used for forwarding and processing logs.
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: elastic-monitoring  # Namespace dedicated to monitoring infrastructure.
spec:
  type: filebeat  # Define the type of Beat.
  version: 8.8.2  # Filebeat version.
  
  # Reference to the Elasticsearch and Kibana instances for data forwarding and visualization.
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana

  config:
    filebeat:
      autodiscover:
        providers:
        - type: kubernetes  # Autodiscover pods for log harvesting.
          node: ${NODE_NAME}  # Current node name.
          hints:
            enabled: true
            default_config:
              type: container
              add_metadata: true  # Add Kubernetes metadata to the logs.
              paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
              # Multiline settings to handle logs spanning multiple lines, common in Java exceptions, etc.
              multiline.pattern: '^[[:space:]]'
              multiline.negate: false
              multiline.match: after

    processors:
    - add_cloud_metadata: {}  # Add metadata about the cloud environment.
    - add_host_metadata: {}  # Add host-level metadata.
    - add_kubernetes_metadata: {}  # Add Kubernetes specific metadata.
    - add_process_metadata:  # Associate logs with their parent process.
        match_pids: 
          - system.process.ppid
        target: system.process.parent

  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat  # Service account for permissions.
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true  # Use host network for richer metadata.
        tolerations:
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            privileged: true  # Required to access logs from all containers.
          volumeMounts:
          # Mounting necessary paths to access various logs.
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumes:
        # Volumes for the container logs.
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
