{{ if .Values.v11y.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: v11y-storage
  labels:
    app.kubernetes.io/name: v11y-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: trustification
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ end }}
