{{ if .Values.guac.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guac-graphql
  labels:
    app.kubernetes.io/name: guac-graphql
    app.kubernetes.io/component: graphql
    app.kubernetes.io/part-of: trustification
spec:
  replicas: {{.Values.graphqlReplicas | default 1  }}
  selector:
    matchLabels:
      app.kubernetes.io/name: guac-graphql
      app.kubernetes.io/component: graphql
      app.kubernetes.io/part-of: trustification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guac-graphql
        app.kubernetes.io/component: graphql
        app.kubernetes.io/part-of: trustification
        metrics: "true"
      annotations:
        config/checksum: {{ include (print $.Template.BasePath "/config/020-ConfigMap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.guac.graphql.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.config.name }}
        - name: guac-config
          configMap:
            name: guac-cm
        {{ include "trustification.http-server-volumes" (dict "root" . "appName" "guac-graphql") | nindent 8 }}
{{- if .Values.guac.database.enabled  }}
      initContainers:
        - image: {{ .Values.guacImage }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: migrate
          command: [ "/bin/sh" ]
          args:
            - -ec
            - |
              /opt/guac/guacmigrate "--db-address" "postgres://${DB_USER}:${DB_PASSWORD}@${PGHOST}:${PGPORT}/${DB_NAME}${TC_PGOPTIONS}" "--db-driver" "postgres" "--db-debug" "true"
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: guac-admin-db
                  key: "db.host"
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: guac-admin-db
                  key: "db.port"
            - name: TC_PGOPTIONS
              valueFrom:
                secretKeyRef:
                  name: guac-admin-db
                  key: "db.options"
                  optional: true
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  # we indeed require the user database, as we set up guac's schema
                  name: guac-user-db
                  key: "db.name"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: guac-admin-db
                  key: "db.user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guac-admin-db
                  key: "db.password"
{{ end }}
      containers:
        - image: {{ .Values.guacImage }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          command: ["/bin/sh"]
          # not sure why --db-migrate=false has to be a single argument, but it won't work otherwise
          args:
            - -ec
            - |
              /opt/guac/guacgql \
{{- if .Values.guac.database.enabled }}
              "--gql-backend" "ent" "--db-address" "postgres://${DB_USER}:${DB_PASSWORD}@${PGHOST}:${PGPORT}/${DB_NAME}${TC_PGOPTIONS}" "--db-driver" "postgres" "--db-debug" "true" "--db-migrate=false"
{{- else }}
              "--gql-backend" "inmem" "--gql-debug" "true"
{{- end }}
          workingDir: "/guac"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{ include "trustification.http-server" . | nindent 12 }}
{{- if .Values.guac.database.enabled  }}
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: guac-admin-db
                  key: "db.host"
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: guac-admin-db
                  key: "db.port"
            - name: TC_PGOPTIONS
              valueFrom:
                secretKeyRef:
                  name: guac-admin-db
                  key: "db.options"
                  optional: true
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: guac-user-db
                  key: "db.name"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: guac-user-db
                  key: "db.user"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guac-user-db
                  key: "db.password"
{{- end }}
          volumeMounts:
            - name: guac-config
              mountPath: /guac
              readOnly: true
            - mountPath: /etc/config
              name: config
            {{ include "trustification.http-server-volume-mounts" . | nindent 12 }}
          resources:
            {{- toYaml .Values.guac.graphql.resources | nindent 12 }}
          ports:
            - containerPort: 8080
              protocol: TCP
{{ end }}
