{{ if .Values.guac.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: guac-graphql
    app.kubernetes.io/component: graphql
    app.kubernetes.io/part-of: trustification
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: guac-graphql-tls
  name: guac-graphql
spec:
  ports:
  - name: endpoint
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: guac-graphql
    app.kubernetes.io/component: graphql
    app.kubernetes.io/part-of: trustification
  type: ClusterIP
{{ end }}
