kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-plugin
data:
  kubernetes-plugin.yaml: |
    kubernetes:
      clusterLocatorMethods:
        - type: config
          clusters:
            - authProvider: serviceAccount
              name: demo-cluster
              skipTLSVerify: true
              serviceAccountToken: ${token}
              url: https://api.{{ .Values.host }}:6443
      customResources:
        - apiVersion: v1
          group: route.openshift.io
          plural: routes
      serviceLocatorMethod:
        type: multiTenant

    dynamicPlugins:
      frontend:
        backstage.plugin-kubernetes:
          mountPoints:
            - mountPoint: entity.page.kubernetes/cards
              importName: EntityKubernetesContent
              config:
                layout:
                  gridColumn: "1 / -1"
                if:
                  anyOf:
                    - hasAnnotation: backstage.io/kubernetes-id
                    - hasAnnotation: backstage.io/kubernetes-namespace
