{{- if or .Values.serverless.enabled .Values.servicemesh.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: networking
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
              {{- if .Values.serverless.enabled }}
                - application: serverless-service
                  namespace: openshift-serverless
                  chart: 
                    name: serverless
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.serverless.chartVersion }}"
              {{- end }}
              {{- if .Values.servicemesh.enabled }}
                - application: servicemesh-service
                  namespace: openshift-servicemesh
                  chart: 
                    name: servicemesh
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.servicemesh.chartVersion }}"
              {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}
{{- end }}