{{- if or .Values.sonarqube.enabled .Values.devhub.enabled .Values.devspaces.enabled .Values.rhoai.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: developer-services
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  goTemplate: true
  goTemplateOptions:
    - "missingkey=error"
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cluster: default
          - list:
              elements:
              {{- if .Values.sonarqube.enabled }}
                - application: sonarqube-service
                  namespace: sonarqube
                  chart: 
                    name: sonarqube
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.sonarqube.chartVersion }}"
                  values: |
                    OpenShift:
                      enabled: "true"
                    serviceAccount:
                      create: "true"
                    postgresql:
                      serviceAccount:
                        enabled: "true"
                    route:
                      enabled: "true"
              {{- end }}
              {{- if .Values.devhub.enabled }}
                - application: developer-hub-service
                  namespace: backstage
                  chart: 
                    name: developerhub
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.devhub.chartVersion }}"
                  values: |
                    host: "{{ `{{ .metadata.labels.domain }}` }}"
                    catalogs:
                      - https://github.com/poc-examples/software-templates/blob/main/catalogs/templates.yaml
                    gitlab:
                      enabled: "{{ .Values.gitlab.enabled }}"
              {{- end }}
              {{- if .Values.devspaces.enabled }}
                - application: devspaces-service
                  namespace: devspaces
                  chart: 
                    name: dev-spaces
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.devspaces.chartVersion }}"
                  values: |
                    domain: "{{ `{{ .metadata.labels.domain }}` }}"
              {{- end }}
              {{- if .Values.rhoai.enabled }}
                - application: rhoai-service
                  namespace: redhat-ods-operator
                  chart: 
                    name: rhoai
                    url: https://poc-examples.github.io/charts
                    version: "{{ .Values.rhoai.chartVersion }}"
              {{- end }}
  template:
    metadata:
      name: "{{ `{{ .application }}` }}"
    spec:
      destination:
        namespace: "{{ `{{ .namespace }}` }}"
        server: "{{ `{{ .server }}` }}"
      source:
        chart: "{{ `{{ .chart.name }}` }}"
        targetRevision: "{{ `{{ .chart.version }}` }}"
        repoURL: "{{ `{{ .chart.url }}` }}"
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: "{{ .Values.gitops.namespace }}"
        syncOptions:
          - CreateNamespace=true
          - Validate=false
  templatePatch: |
    spec:
      source:
        helm:
        {{ `{{- if (index . "values") }}` }}
          values: |
            {{ `{{- .values | nindent 12 }}` }}
        {{ `{{- end }}` }}
{{- end }}