apiVersion: apps/v1
kind: Deployment
metadata:
  name: vexination-api
  labels:
    app.kubernetes.io/name: vexination-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: trustification
{{ if eq "enabled" .Values.vexination.api.tracing }}
  annotations:
    sidecar.jaegertracing.io/inject: "true"
{{ end }}
spec:
  replicas: {{ .Values.vexination.api.replicas | default 1 }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: vexination-api
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: trustification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vexination-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: trustification
        metrics: "true"
      annotations:
        config/checksum: {{ include (print $.Template.BasePath "/config/020-ConfigMap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ .Values.config.name }}
        {{ include "trustification.http-server-volumes" (dict "root" . "appName" "vexination-api") | nindent 8 }}
      containers:
        - image: {{ .Values.trustImage }}:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: service
          command: ["/trust"]
          args:
            - "vexination"
            - "api"
            - "-p"
            - "8080"
            - "--index-mode"
            - "{{ .Values.vexination.indexMode }}"
            - "--auth-configuration"
            - "/etc/config/auth.yaml"
          env:
            - name: RUST_LOG
              value: {{ default "info" .Values.vexination.api.logLevel }}
            {{ include "trustification.storage-env" ( dict "root" . "config" .Values.vexination ) | nindent 12 }}
            {{ include "trustification.http-server" . | nindent 12 }}
            - name: INFRASTRUCTURE_ENABLED
              value: "true"
            - name: INFRASTRUCTURE_BIND
              value: "[::]:9010"
            - name: TRACING
              value: {{ default "disabled" .Values.vexination.api.tracing }}
            - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
              value: "32"
            - name: OTEL_TRACES_SAMPLER
              value: parentbased_traceidratio
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0.1"
            - name: INDEX_SYNC_INTERVAL
              value: {{ .Values.vexination.api.indexSyncInterval | default "1800s" }}
{{ if not .Values.disableSwaggerOidc }}
            - name: SWAGGER_UI_OIDC_ISSUER_URL
              {{ include "trustification.authentication-frontend-issuer-url" . | nindent 14 }}
{{ end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - mountPath: /etc/config
              name: config
            {{ include "trustification.http-server-volume-mounts" . | nindent 12 }}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9010
              protocol: TCP
              name: infra
          resources:
            {{- toYaml .Values.vexination.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9010
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9010
            initialDelaySeconds: 2
          startupProbe:
            httpGet:
              path: /health/startup
              port: 9010
