kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: backstage-config
data:
  service.yaml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: backstage-developer-hub
    spec:
      type: ClusterIP
      selector:
        rhdh.redhat.com/app: backstage-developer-hub
      ports:
        - name: http-backend
          port: 80
          targetPort: backend
  route.yaml: |
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: backstage-developer-hub
    spec:
      port:
        targetPort: http-backend
      path: /
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: backstage-developer-hub
  deployment.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backstage-developer-hub
    spec:
      replicas: 1
      selector:
        matchLabels:
          rhdh.redhat.com/app: backstage-developer-hub
      template:
        metadata:
          labels:
            rhdh.redhat.com/app: backstage-developer-hub
        spec:
          automountServiceAccountToken: false
          volumes:
            - ephemeral:
                volumeClaimTemplate:
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 2Gi
              name: dynamic-plugins-root
            - name: dynamic-plugins-npmrc
              secret:
                defaultMode: 420
                optional: true
                secretName: dynamic-plugins-npmrc
          initContainers:
            - name: remove-lost-found
              image: busybox
              command: ['sh', '-c', 'rm -rf /dynamic-plugins-root/lost+found && echo "Purge of lost+found was successful"']
              volumeMounts:
                - mountPath: /dynamic-plugins-root
                  name: dynamic-plugins-root
            - name: install-dynamic-plugins
              command:
                - ./install-dynamic-plugins.sh
                - /dynamic-plugins-root
              image: quay.io/janus-idp/backstage-showcase:latest
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
              env:
                - name: NPM_CONFIG_USERCONFIG
                  value: /opt/app-root/src/.npmrc.dynamic-plugins
                - name: SKIP_INTEGRITY_CHECK
                  value: 'true'
              volumeMounts:
                - mountPath: /dynamic-plugins-root
                  name: dynamic-plugins-root
                - mountPath: /opt/app-root/src/.npmrc.dynamic-plugins
                  name: dynamic-plugins-npmrc
                  readOnly: true
                  subPath: .npmrc
                - name: dynamic-plugins
                  readOnly: true
                  mountPath: /opt/app-root/src/dynamic-plugins.yaml
                  subPath: dynamic-plugins.yaml
              workingDir: /opt/app-root/src
              resources:
                requests:
                  cpu: 250m
                  memory: 256Mi
                limits:
                  cpu: 1000m
                  memory: 2.5Gi
                  ephemeral-storage: 5Gi
          containers:
            - name: backstage-backend
              image: quay.io/janus-idp/backstage-showcase:latest
              imagePullPolicy: IfNotPresent
              args:
                - "--config"
                - "dynamic-plugins-root/app-config.dynamic-plugins.yaml"
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthcheck
                  port: 7007
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 2
                timeoutSeconds: 2
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthcheck
                  port: 7007
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 2
              ports:
                - name: backend
                  containerPort: 7007
              env:
                - name: APP_CONFIG_backend_listen_port
                  value: "7007"
              volumeMounts:
                - mountPath: /opt/app-root/src/dynamic-plugins-root
                  name: dynamic-plugins-root
              resources:
                requests:
                  cpu: 250m
                  memory: 256Mi
                limits:
                  cpu: 1000m
                  memory: 2.5Gi
                  ephemeral-storage: 5Gi
