---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: backend-password
spec:
  length: 16
  symbols: 1
  symbolCharacters: "@"
  digits: 5
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "backend-credentials"
spec:
  refreshInterval: "0"
  target:
    name: backend-credentials
  dataFrom:
  - rewrite:
      - regexp:
          source: "password"
          target: "DEVHUB_BACKEND_SECRET"
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "backend-password"
