---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-password
spec:
  length: 20
  symbols: 2
  symbolCharacters: "!@#"
  digits: 4
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "postgres-credentials"
spec:
  refreshInterval: "0"
  target:
    name: postgres-credentials
    template:
      mergePolicy: Merge
      engineVersion: v2
      data:
        POSTGRES_HOST: postgres.backstage.svc.cluster.local
        POSTGRES_USER: postgres
        POSTGRES_PORT: "5432"
        PGSSLMODE: disable
  dataFrom:
  - rewrite:
      - regexp:
          source: "password"
          target: "POSTGRES_PASSWORD"
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: "postgres-password"
