{{- if .Values.gitlab.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: github-plugin
data:
  github-plugin.yaml: |
    gitlab:
      defaultCodeOwnersPath: .gitlab/CODEOWNERS
      defaultReadmePath: .gitlab/README.md
      allowedKinds:
        - Component
        - System
        - API
        - Resource
        - Location
        - Template
      proxySecure: false

    integrations:
      gitlab:
        - host: gitlab.com
          token: ${GITLAB_TOKEN}
          apiBaseUrl: "https://gitlab.{{ .Values.host }}/api/v4"
          baseUrl: "https://gitlab.{{ .Values.host }}"
        - host: gitlab.{{ .Values.host }}
          token: ${GITLAB_TOKEN}
          apiBaseUrl: "https://gitlab.{{ .Values.host }}/api/v4"
          baseUrl: "https://gitlab.{{ .Values.host }}"

    dynamicPlugins:
      frontend:
        immobiliarelabs.backstage-plugin-gitlab:
          mountPoints:
            - mountPoint: entity.page.overview/cards
              importName: EntityGitlabMergeRequestStatsCard
              config:
                layout:
                  gridColumnEnd:
                    lg: "span 4"
                    md: "span 6"
                    xs: "span 12"
                if:
                  allOf:
                    - isGitlabAvailable
            - mountPoint: entity.page.ci/cards
              importName: EntityGitlabPipelinesTable
              config:
                layout:
                  gridColumn: "1 / -1"
                if:
                  allOf:
                    - isGitlabAvailable
            - mountPoint: entity.page.issues/cards
              importName: EntityGitlabIssuesTable
              config:
                layout:
                  gridColumn: "1 / -1"
                if:
                  allOf:
                    - isGitlabAvailable
            - mountPoint: entity.page.pull-requests/cards
              importName: EntityGitlabMergeRequestsTable
              config:
                layout:
                  gridColumn: "1 / -1"
                if:
                  allOf:
                    - isGitlabAvailable
{{- end }}