apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-secret-openshift
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-client-secret-openshift
  data:
  - secretKey: CLIENT_SECRET
    remoteRef:
      key: keycloak-client-secret-openshift
      property: CLIENT_SECRET
  - secretKey: CLIENT_ID
    remoteRef:
      key: keycloak-client-secret-openshift
      property: CLIENT_ID