apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/modelServingSupport: '["single"]'
  labels:
    opendatahub.io/dashboard: "true"
  name: dual-gpu-vllm-runtime-template
  namespace: redhat-ods-applications
objects:
- apiVersion: serving.kserve.io/v1alpha1
  kind: ServingRuntime
  metadata:
    annotations:
      opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
      openshift.io/display-name: Dual GPU vLLM ServingRuntime for KServe
    labels:
      opendatahub.io/dashboard: "true"
    name: dual-gpu-vllm-runtime
  spec:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
    containers:
    - args:
      - --port=8080
      - --model=/mnt/models
      - --served-model-name={{ `{{.Name}}` }}
      - --distributed-executor-backend=mp
      - --tensor_parallel_size=2
      command:
      - python
      - -m
      - vllm.entrypoints.openai.api_server
      - --trust-remote-code
      env:
      - name: HF_HOME
        value: /tmp/hf_home
      image: quay.io/modh/vllm@sha256:e14cae9114044dc9fe71e99c3db692a892b2caffe04283067129ab1093a7bde5
      name: kserve-container
      ports:
      - containerPort: 8080
        protocol: TCP
    multiModel: false
    supportedModelFormats:
    - autoSelect: true
      name: vLLM