{{ if .Values.createRoutes }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    {{- .Values.spog.api.routeAnnotations | default .Values.default.routeAnnotations | toYaml | nindent 4 }}
  labels:
    app.kubernetes.io/name: spog-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: trustification
  name: spog-api
spec:
  host: "api.{{ .Values.domain }}"
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: endpoint
  to:
    kind: Service
    name: spog-api
    weight: 100
  wildcardPolicy: None
{{ end }}
