{{- if .Values.ssoDefaults }}
---
kind: Secret
apiVersion: v1
metadata:
  name: sso-admin
  labels:
    app.kubernetes.io/name: sso-admin
    app.kubernetes.io/component: sso
    app.kubernetes.io/part-of: sso
data:
  password: {{ .Values.sso.admin | default "admin123456" | b64enc }}
---
kind: Secret
apiVersion: v1
metadata:
  name: sso-realm-admin
  labels:
    app.kubernetes.io/name: sso-realm-admin
    app.kubernetes.io/component: sso
    app.kubernetes.io/part-of: sso
data:
  password: {{ .Values.sso.realmAdmin | default "admin123456" | b64enc }}
---
kind: Secret
apiVersion: v1
metadata:
  name: sso-postgres
  labels:
    app.kubernetes.io/name: sso-postgres
    app.kubernetes.io/component: sso
    app.kubernetes.io/part-of: sso
data:
  password: {{ .Values.sso.postgresPassword | default "admin123456" | b64enc }}
  postgres-password: {{ .Values.sso.postgresPassword | default "admin123456" | b64enc }}
---
kind: Secret
apiVersion: v1
metadata:
  name: oidc-client-walker
  labels:
    app.kubernetes.io/name: oidc-client-walker
    app.kubernetes.io/component: sso
    app.kubernetes.io/part-of: sso
data:
  client-secret: {{ "5460cc91-4e20-4edd-881c-b15b169f8a79" | b64enc }} # not a secret
---
kind: Secret
apiVersion: v1
metadata:
  name: oidc-client-testing-manager
  labels:
    app.kubernetes.io/name: oidc-client-testing-manager
    app.kubernetes.io/component: sso
    app.kubernetes.io/part-of: sso
data:
  client-secret: {{ "ca48053c-3b82-4650-a98d-4cace7f2d567" | b64enc }} # not a secret
---
kind: Secret
apiVersion: v1
metadata:
  name: oidc-client-testing-user
  labels:
    app.kubernetes.io/name: oidc-client-testing-user
    app.kubernetes.io/component: sso
    app.kubernetes.io/part-of: sso
data:
  client-secret: {{ "0e6bf990-43b4-4efb-95d7-b24f2b94a525" | b64enc }} # not a secret
{{ end }}