{{- if .Values.dataset.enabled }}
kind: Job
apiVersion: batch/v1
metadata:
  name: apply-dataset
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
    helm.sh/hook-weight: "20"
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/name: apply-dataset
    app.kubernetes.io/component: init
    app.kubernetes.io/part-of: trustification

spec:
  backoffLimit: 1000
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 600
  template:
    spec:

      restartPolicy: OnFailure

      containers:
        - name: run
          image: {{ .Values.trustImage }}:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}

          command: ["/usr/bin/bash"]
          args:
            - "-ce"
            - |
              /trust bombastic walker --sink https://sbom.{{ .Values.domain }} --source file:/data/sbom
              /trust vexination walker --sink https://vex.{{ .Values.domain }}/api/v1/vex --source file:/data/csaf

          env:
            {{- include "trustification.authentication-client" ( dict "root" . "clientId" "walker" ) | nindent 16 }}
{{ end }}
