{{ if .Values.dataset.enabledJob }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: apply-dataset-job
  labels:
    app.kubernetes.io/name: apply-dataset-job
    app.kubernetes.io/component: init
    app.kubernetes.io/part-of: trustification
spec:
  schedule: {{ .Values.dataset.scheduleJob | default "0 1 * * *" }}
  suspend: {{ .Values.dataset.suspendJob | default true }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: apply-dataset-manual-job
            app.kubernetes.io/component: init
            app.kubernetes.io/part-of: trustification
        spec:
          restartPolicy: OnFailure

          containers:
            - name: run
              image: {{ .Values.trustImage }}:{{ .Values.release }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}

              command: [ "/usr/bin/bash" ]
              args:
                - "-ce"
                - |
                  set -e
                  /trust bombastic walker --sink https://sbom.{{ .Values.domain }} --source file:/data/sbom
                  /trust vexination walker --sink https://vex.{{ .Values.domain }}/api/v1/vex --source file:/data/csaf

              env:
                {{- include "trustification.authentication-client" ( dict "root" . "clientId" "walker" ) | nindent 16 }}
{{ end }}
