apiVersion: v1
kind: ConfigMap
metadata:
  name: guac-cm
  labels:
    app.kubernetes.io/name: guac-cm
    app.kubernetes.io/component: cm
    app.kubernetes.io/part-of: trustification
data:
  guac.yaml: |
    # CSub setup
    csub-addr: "guac-collectsub.{{ $.Release.Namespace }}.svc.cluster.local:2782"
    csub-listen-port: 2782

    # GQL setup
    gql-listen-port: 8080
    gql-debug: {{ $.Values.guac.graphql.debug }}
    gql-test-data: false
    gql-addr: http://guac-graphql.{{ $.Release.Namespace }}.svc:8080/query

    # Collector behavior
    service-poll: false
    use-csub: true
