apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: "{{ .Values.namespace }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  affinity: {}
  certController:
    affinity: {}
    create: true
    deploymentAnnotations: {}
    extraArgs: {}
    extraEnv: []
    fullnameOverride: ''
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/external-secrets/external-secrets
      tag: ''
    imagePullSecrets: []
    nameOverride: ''
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    priorityClassName: ''
    prometheus:
      enabled: false
      service:
        port: 8080
    rbac:
      create: true
    requeueInterval: 5m
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    securityContext: {}
    serviceAccount:
      annotations: {}
      create: true
      name: ''
    tolerations: []
  concurrent: 1
  controllerClass: ''
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
  createOperator: true
  deploymentAnnotations: {}
  extraArgs: {}
  extraEnv: []
  fullnameOverride: ''
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/external-secrets/external-secrets
    tag: ''
  imagePullSecrets: []
  installCRDs: false
  leaderElect: false
  nameOverride: ''
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  priorityClassName: ''
  processClusterExternalSecret: true
  processClusterStore: true
  prometheus:
    enabled: false
    service:
      port: 8080
  rbac:
    create: true
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  scopedNamespace: ''
  scopedRBAC: false
  securityContext: {}
  serviceAccount:
    annotations: {}
    create: true
    name: ''
  tolerations: []
  webhook:
    affinity: {}
    certCheckInterval: 5m
    certDir: /tmp/certs
    create: true
    deploymentAnnotations: {}
    extraArgs: {}
    extraEnv: []
    fullnameOverride: ''
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/external-secrets/external-secrets
      tag: ''
    imagePullSecrets: []
    nameOverride: ''
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    priorityClassName: ''
    prometheus:
      enabled: false
      service:
        port: 8080
    rbac:
      create: true
    replicaCount: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    securityContext: {}
    serviceAccount:
      annotations: {}
      create: true
      name: ''
    tolerations: []
