---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: application-post-hook
rules:
- apiGroups: [
    "apps"
  ]
  resources: [
    "deployments"
  ]
  verbs: [
    "get", 
    "list", 
    "watch"
  ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: application-post-hook-binding
subjects:
- kind: ServiceAccount
  name: ansible-runner
  namespace: external-secrets
roleRef:
  kind: Role
  name: application-post-hook
  apiGroup: rbac.authorization.k8s.io
