apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "{{ .Values.namespace }}"
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: "{{ .Values.namespace }}-operator"
  source: community-operators
  sourceNamespace: openshift-marketplace
