---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ctlog-keys-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: ctlog-ctlog-keys
    template:
      type: generic
  data:
    - secretKey: "private"
      remoteRef:
        key: ctlog
        property: "private"
    - secretKey: "public"
      remoteRef:
        key: ctlog
        property: "public"
    - secretKey: "passphrase"
      remoteRef:
        key: ctlog
        property: "passphrase"
