---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rekor-signing-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: rekor-signing-secret
    template:
      metadata:
        labels:
          rhtas.redhat.com/signing-secret: 'true'
      type: generic
  data:
    - secretKey: "signing.pub"
      remoteRef:
        key: rekor
        property: "pub"
    - secretKey: "signing.key"
      remoteRef:
        key: rekor
        property: "key"
