---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-key-pair
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: ca-key-pair
    template:
      type: generic
  data:
    - secretKey: "ca.key"
      remoteRef:
        key: cert
        property: "ca.key"
    - secretKey: "ca.crt"
      remoteRef:
        key: cert
        property: "ca.crt"
    - secretKey: "passphrase"
      remoteRef:
        key: cert
        property: "password"
