# apiVersion: rhtas.redhat.com/v1alpha1
# kind: Securesign
# metadata:
#   name: secure-sign
#   labels:
#     app.kubernetes.io/instance: secure-sign
#     app.kubernetes.io/name: secure-sign
#     app.kubernetes.io/part-of: trusted-artifact-signer
# spec:
#   analytics: false
#   ctlog:
#     privateKeyPasswordRef:
#       name: signing-secret
#       key: cosign.password
#     privateKeyRef:
#       key: cosign.key
#       name: signing-secret
#     publicKeyRef:
#       key: cosign.pub
#       name: signing-secret
#   fulcio:
#     certificate:
#       commonName: fulcio.apps.j3w50o9m.eastus.aroapp.io
#       organizationEmail: admin@redhat.com
#       organizationName: Red Hat
#     config:
#       OIDCIssuers:
#         - ClientID: trusted-artifact-signer
#           Issuer: 'https://your-oidc-issuer-url'
#           IssuerURL: 'https://your-oidc-issuer-url'
#           Type: email
#     externalAccess:
#       enabled: true
#     monitoring:
#       enabled: false
#   rekor:
#     backFillRedis:
#       enabled: true
#       schedule: 0 0 * * *
#     externalAccess:
#       enabled: true
#     monitoring:
#       enabled: false
#     pvc:
#       retain: true
#       size: 5Gi
#     rekorSearchUI:
#       enabled: true
#     signer:
#       keyRef:
#         name: signing-secret
#         key: cosign.key
#       passwordRef:
#         key: cosign.password
#         name: signing-secret
#   trillian:
#     database:
#       create: true
#       pvc:
#         retain: true
#         size: 5Gi
#   tuf:
#     externalAccess:
#       enabled: true
#     keys:
#       - name: cosign.pub
#       - name: cosign.pub
#       - name: fulcio_v1.crt.pem
#     port: 80
