apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  name: developers
rules:
- apiGroups:
  - kafka.strimzi.io
  resources:
  - kafkas
  verbs:
  - list
- apiGroups:
  - opentelemetry.io
  resources:
  - opentelemetrycollectors
  - instrumentations
  verbs:
  - create
  - get
  - list
  - update
  - delete
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreamimports
  - imagestreamimages
  - imagestreamtags
  verbs:
  - create
  - get
  - list
  - delete
  - update
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  - builds
  verbs:
  - create
  - get
  - list
  - delete
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - delete
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - delete